### PR TITLE
Fix 100% CPU usage

### PR DESCRIPTION
**Pull request by renehoelbling**
Add sleep to avoid busy waiting

### CODE REVIEW

**Comment by renehoelbling** [comment]
[100% CPU usage by webbridge investigation](https://trello.com/c/Y7OBDuAO/1849-100-cpu-usage-by-webbridge-investigation)

**Review by meyerj — COMMENTED** [review]
Probably not necessary anymore. Additionally, upstream [RobotWebTools/rclnodejs](https://github.com/RobotWebTools/rclnodejs) does not have this code anymore ([diff](https://github.com/Intermodalics/rclnodejs/compare/fix/cpu_usage...RobotWebTools:develop#diff-12041050be04f75f5ddf384953b11422)) and an upgrade to a newer version might also have solved the 100% CPU usage issue if there is nothing to do.

**Comment by renehoelbling** [comment]
They changed their code a little but the main reasons for the 100% CPU usage issue is still there and moved to [WaitForReadyCallbacks](https://github.com/RobotWebTools/rclnodejs/blob/develop/src/executor.cpp#L166).

**Comment by meyerj** [comment]
> They changed their code a little but the main reasons for the 100% CPU usage issue is still there and moved to [WaitForReadyCallbacks](https://github.com/RobotWebTools/rclnodejs/blob/develop/src/executor.cpp#L166).

:+1:

In this case the PR is still valid, and we should also consider to submit a pull request to [RobotWebTools/rclnodejs](https://github.com/RobotWebTools/rclnodejs).

**Comment by meyerj** [comment]
Fixed in https://github.com/RobotWebTools/rclnodejs/pull/763 and version 0.18.0, but probably not for ROS Dashing. Anyway, we are going to upgrade to Foxy soon.

**Pull request closed without merging**
